on:
  push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest", "macos-latest"]
        test:
          - pyepics
          - epicscorelibs pyepics
          - epicscorelibs pyepics p4p
          - aioca p4p
          - pvapy
          - pyepics pvapy aioca p4p
          - aioca p4p epicscorelibs pyepics
          - epicscorelibs pyepics aioca p4p
          - aioca p4p pyepics
          - aioca p4p pvapy

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install epicscorelibs pyepics aioca pvapy p4p

      - uses: mdavidsaver/ci-core-dumper@master

      - shell: bash
        run: |
          ulimit -c unlimited
          ./run_tests.sh ${{ matrix.test }}

