on:
  push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        test:
          - pyepics
          - pvapy
          - pyepics pvapy aioca p4p
          - aioca p4p epicscorelibs pyepics
          - epicscorelibs pyepics aioca p4p
          - aioca p4p pyepics
          - aioca p4p pvapy

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install ${{ matrix.test }}

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install gdb

      - shell: bash
        run: ./run_tests.sh ${{ matrix.test }}

