on:
  push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        test:
          - pyepics pvapy aioca p4p
          - aioca p4p epicscorelibs pyepics
          - pyepics epicscorelibs aioca p4p
          - aioca p4p pyepics
          - aioca p4p pvapy

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - if: ${{ matrix.os }} == "ubuntu-latest"
        run: sudo apt-get install gdb

      - if: ${{ matrix.os }} == "macos-latest"
        run: brew install gdb

      - shell: bash
        run: |
          pip install ${{ matrix.test }}
          gdb python -ex "run test_clients.py ${{ matrix.test }}" -ex "thread apply all bt" -ex "set pagination 0" -ex "info proc mappings" -ex "info reg" -ex "disassemble" -ex 'print /x * (int*) $rsp' -batch

